# Generated by Django 3.1.8 on 2021-09-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docnum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officaldoc',
            name='title',
            field=models.CharField(default='Null', max_length=300),
            preserve_default=False,
        ),
    ]
