# Generated by Django 3.1.8 on 2021-09-17 02:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docnum', '0002_officaldoc_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='officaldoc',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
