# Generated by Django 3.1.8 on 2022-09-21 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docnum', '0005_auto_20210917_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=10)),
                ('fullsn', models.CharField(max_length=30, unique=True)),
                ('senddept', models.CharField(max_length=100)),
                ('sendsn', models.CharField(max_length=100, unique=True)),
                ('senddate', models.DateField()),
                ('abstract', models.CharField(max_length=500)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivedocs', to=settings.AUTH_USER_MODEL)),
                ('rcvcomp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivedocs', to='docnum.company')),
            ],
        ),
    ]
