# Generated by Django 3.1.8 on 2022-12-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docnum', '0007_contractcate_historicalcontractcate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
