# Generated by Django 3.1.8 on 2022-12-21 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docnum', '0008_contractstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTaxStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('add_time', models.DateTimeField(blank=True, editable=False)),
                ('update_time', models.DateTimeField(blank=True, editable=False)),
                ('order', models.IntegerField(db_index=True)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical project',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalContract',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('add_time', models.DateTimeField(blank=True, editable=False)),
                ('update_time', models.DateTimeField(blank=True, editable=False)),
                ('sn', models.CharField(db_index=True, max_length=17)),
                ('sign_date', models.DateField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('counterparty', models.CharField(max_length=100)),
                ('counter_dept', models.CharField(max_length=50)),
                ('counter_contact', models.CharField(max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='docnum.contractcate')),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('comp', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='docnum.company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manage_dept', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='docnum.department')),
                ('manager', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='docnum.project')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='docnum.contractstatus')),
                ('tax_status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='docnum.contracttaxstatus')),
            ],
            options={
                'verbose_name': 'historical contract',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('sn', models.CharField(max_length=17, unique=True)),
                ('sign_date', models.DateField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('counterparty', models.CharField(max_length=100)),
                ('counter_dept', models.CharField(max_length=50)),
                ('counter_contact', models.CharField(max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='docnum.contractcate')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='docnum.company')),
                ('manage_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='docnum.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='docnum.project')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='docnum.contractstatus')),
                ('tax_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='docnum.contracttaxstatus')),
            ],
            options={
                'ordering': ['-add_time'],
            },
        ),
    ]
