# Generated by Django 3.1.8 on 2023-01-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docnum', '0010_auto_20221223_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['plmsn']},
        ),
        migrations.AddField(
            model_name='company',
            name='plmsn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
