# Generated by Django 3.1.8 on 2022-12-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docnum', '0011_company_plmsn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='plmsn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
