# Generated by Django 3.1.8 on 2023-05-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docnum', '0017_auto_20230502_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='officaldoc',
            name='invalid_reason',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='receivedoc',
            name='invalid_reason',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
