from django.urls import path, include
from . import views, ajax

urlpatterns = [
    path('non_auth_error/', views.non_auth_page, name="Non_auth_error"),
    path('company/', views.comp_list, name="Comp_index"),
    path('company/<int:comp_id>/', views.comp_detail, name="Comp_detail"),
    path('company/<int:comp_id>/switch/', views.switch_comp, name="Comp_switch"),
    path('company/<int:comp_id>/delete/', views.comp_del, name="Comp_delete"),
    path('department/', views.dept_list, name="Dept_list"),
    path('departnemt/<int:dept_id>/switch/', views.switch_dept, name="Dept_switch"),
    path('departnemt/<int:dept_id>/delete/', views.dept_del, name="Dept_delete"),
    path('ajax/getdocnum/', ajax.getdocnum),
    path('send/', views.doc_list, name="Doc_index"),
    path('send/export/', views.send_export, name="Send_Export"),
    path('send/add/', views.doc_add_v2, name="Doc_add"),
    path('send/<int:id_docnum>/', views.doc_result, name="Doc_add_result"),
    path('send/<int:id_docnum>/disable/', views.doc_disable, name="Doc_disable"),
    path('send/<int:id_docnum>/editremark/', views.doc_editremark, name="Doc_editremark"),
    path('receive/', views.receivedoc_list, name="Receive_List"),
    path('receive/export/', views.receive_export, name="Receive_Export"),
    path('receive/add/', views.receivedoc_add, name="Receive_add"),
    path('receive/<int:id_rcvdoc>/', views.receivedoc_result, name="Receive_result"),
    path('receive/<int:id_rcvdoc>/delete/', views.recivedoc_disable, name="Receive_disable"),
    path('receive/<int:id_rcvdoc>/editremark/', views.recivedoc_editremark, name="Receive_editremark"),
    path('contract/', views.contract_list, name="Contract_list"),
    path('contract/add/', views.contract_add, name="Contract_add"),
    path('contract/export/', views.contracts_export2, name="Contract_Export"),
    path('contract/<int:contra_id>/', views.contract_detail, name='Contract_detail'),
    path('contract/<int:contra_id>/update/', views.contract_update, name='Contract_update'),
    path('contract/<int:contra_id>/disable/', views.contract_disable, name='Contract_disable'),
    path('contract/<int:contra_id>/confirm/', views.contract_confirm, name='Contract_confirm'),
    path('contract/<int:contra_id>/archive/', views.contract_archive, name='Contract_archive'),
    path('contract/<int:contra_id>/addextend/', views.contract_extend, name='Contract_extend'),
    path('contract/<int:contra_id>/loan/', views.contract_loan, name='Contract_loan'),
    path('contract/<int:contra_id>/expswitch', views.contract_expired_switch, name='ContractEXP_switch'),
    path('loan/export/', views.loans_export2, name='Loan_export'),
    path('loan/<int:loan_id>/lentout/', views.loan_lendout, name="Loan_lend"),
    path('loan/<int:loan_id>/backin/', views.loan_backin, name="Loan_back"),
    path('loan/<int:loan_id>/cancel/', views.loan_cancel, name="Loan_cancel"),
]